In [51]:
import numpy as np

In [9]:
world_alcohol = np.genfromtxt("G:/机器学习/唐宇迪机器学习视频/机器学习算法配套案例实战/Python库代码（4个）/1-科学计算库numpy/world_alcohol.txt", delimiter=",", dtype=str)
print(type(world_alcohol))
print(world_alcohol)

<class 'numpy.ndarray'>
[['Year' 'WHO region' 'Country' 'Beverage Types' 'Display Value']
 ['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ..., 
 ['1987' 'Africa' 'Malawi' 'Other' '0.75']
 ['1989' 'Americas' 'Bahamas' 'Wine' '1.5']
 ['1985' 'Africa' 'Malawi' 'Spirits' '0.31']]


In [11]:
vector = np.array([5, 10, 15, 20])
print(vector[0:3])

[ 5 10 15]


In [20]:
matrix =  np.array([[5,10,15],
                   [20,25,30],
                   [35,40,45]])
print(matrix[:, 1])  #取所有行，和第1列的数据
print(matrix[:, 0:2])
print(matrix[0:2, 1:3])

[10 25 40]
[[ 5 10]
 [20 25]
 [35 40]]
[[10 15]
 [25 30]]


In [21]:
vector == 10

array([False,  True, False, False], dtype=bool)

In [22]:
matrix == 25

array([[False, False, False],
       [False,  True, False],
       [False, False, False]], dtype=bool)

In [27]:
equal_to_ten = vector == 10
print(equal_to_ten)
print(vector[equal_to_ten])  #利用bool类型作为数组下标

[False  True False False]
[10]


In [30]:
second_column_25 = (matrix[:, 1] == 25)
print(second_column_25)
print(matrix[second_column_25, :])

[False  True False]
[[20 25 30]]


In [33]:
equal_to_ten_and_five = (vector == 10) & (vector == 5)
print(equal_to_ten_and_five)

[False False False False]


In [34]:
equal_to_ten_or_five = (vector == 10) | (vector == 5)
print(equal_to_ten_or_five)

[ True  True False False]


In [35]:
vector[equal_to_ten_or_five] = 50
print(vector)

[50 50 15 20]


In [41]:
vector = np.array(["1", "2", "3"])
print(vector.dtype)
print(vector)
vector = vector.astype(float)
print(vector.dtype)
print(vector)

<U1
['1' '2' '3']
float64
[ 1.  2.  3.]


In [45]:
vector  = np.array([5,10,15,20])
print(vector.min())

5


In [49]:
matrix =  np.array([[5,10,15],
                   [20,25,30],
                   [35,40,45]])
matrix.sum(axis=1)  #对行进行求和

array([ 30,  75, 120])

In [50]:
matrix.sum(axis=0)  #对列进行求和

array([60, 75, 90])

In [54]:
print(np.arange(15))
a = np.arange(15).reshape(3, 5)
a

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [55]:
a.shape

(3, 5)

In [57]:
#the number of axes (dimensions) of the array
a.ndim

2

In [58]:
a.dtype.name

'int32'

In [59]:
a.size

15

In [60]:
np.zeros((3, 4))  #初始化矩阵

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [62]:
np.ones((2,3,4), dtype=np.int32)  #出事化矩阵的同时，可以指定他的类型

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [63]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [65]:
np.random.random((2, 3))  #numpy中random模块中的random函数

array([[ 0.60396226,  0.1070227 ,  0.7900518 ],
       [ 0.90165475,  0.6441092 ,  0.94833701]])

In [67]:
from numpy import pi
np.linspace(0, 2*pi, 100)

array([ 0.        ,  0.06346652,  0.12693304,  0.19039955,  0.25386607,
        0.31733259,  0.38079911,  0.44426563,  0.50773215,  0.57119866,
        0.63466518,  0.6981317 ,  0.76159822,  0.82506474,  0.88853126,
        0.95199777,  1.01546429,  1.07893081,  1.14239733,  1.20586385,
        1.26933037,  1.33279688,  1.3962634 ,  1.45972992,  1.52319644,
        1.58666296,  1.65012947,  1.71359599,  1.77706251,  1.84052903,
        1.90399555,  1.96746207,  2.03092858,  2.0943951 ,  2.15786162,
        2.22132814,  2.28479466,  2.34826118,  2.41172769,  2.47519421,
        2.53866073,  2.60212725,  2.66559377,  2.72906028,  2.7925268 ,
        2.85599332,  2.91945984,  2.98292636,  3.04639288,  3.10985939,
        3.17332591,  3.23679243,  3.30025895,  3.36372547,  3.42719199,
        3.4906585 ,  3.55412502,  3.61759154,  3.68105806,  3.74452458,
        3.8079911 ,  3.87145761,  3.93492413,  3.99839065,  4.06185717,
        4.12532369,  4.1887902 ,  4.25225672,  4.31572324,  4.37

In [75]:
#the product operator * operates element wise in Numpy arrays
a = np.array([20,30,40,50])
b = np.arange(4)
print(a)
print(b)
c = a-b
print(c)
print(b**2)
print(a<35)

[20 30 40 50]
[0 1 2 3]
[20 29 38 47]
[0 1 4 9]
[ True  True False False]


In [83]:
A = np.array([[1,1],
            [0,1]])
B = np.array([[2,0],
             [3,4]])

print(A*B)  #矩阵对应位置的元素进行相乘
print('----------')
print(A.dot(B))  #矩阵的乘法
print('----------')
print(np.dot(A, B))  #矩阵的乘法

[[2 0]
 [0 4]]
----------
[[5 4]
 [3 4]]
----------
[[5 4]
 [3 4]]


In [87]:
B = np.arange(3)
print(B)
print(np.exp(B))
print(np.sqrt(B))

[0 1 2]
[ 1.          2.71828183  7.3890561 ]
[ 0.          1.          1.41421356]


In [101]:
a = np.floor(10*np.random.random((3,4)))  #floor是向下取整的函数
print(a)
print('----------')
print(a.ravel())  #将矩阵拉成一个向量
print('----------')
a.shape = (6, 2)  #可以对矩阵进行任意维度的转换
print(a)
print('----------')
print(a.T)
print('----------')
print(a.reshape(4, -1))  #对于二维矩阵，如果确定了行数，那么他的列数自然就定下来了

[[ 0.  6.  9.  5.]
 [ 5.  1.  4.  7.]
 [ 6.  7.  2.  3.]]
----------
[ 0.  6.  9.  5.  5.  1.  4.  7.  6.  7.  2.  3.]
----------
[[ 0.  6.]
 [ 9.  5.]
 [ 5.  1.]
 [ 4.  7.]
 [ 6.  7.]
 [ 2.  3.]]
----------
[[ 0.  9.  5.  4.  6.  2.]
 [ 6.  5.  1.  7.  7.  3.]]
----------
[[ 0.  6.  9.]
 [ 5.  5.  1.]
 [ 4.  7.  6.]
 [ 7.  2.  3.]]


In [103]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))
print(a)
print('----------')
print(b)
print('----------')
print(np.hstack((a, b)))
print('----------')
print(np.vstack((a, b)))

[[ 6.  9.]
 [ 2.  5.]]
----------
[[ 8.  7.]
 [ 2.  3.]]
----------
[[ 6.  9.  8.  7.]
 [ 2.  5.  2.  3.]]
----------
[[ 6.  9.]
 [ 2.  5.]
 [ 8.  7.]
 [ 2.  3.]]


In [114]:
a = np.floor(10*np.random.random((2, 12)))
print(a)
print('----------')
print(np.hsplit(a, 3))  #对矩阵横着平均切三份
print('----------')
print(np.hsplit(a, (3, 4)))  #Split a after the third and the fourth column
print('----------')
b = a.T
print(b)
print('----------')
print(np.vsplit(b, 3))
print('----------')
print(np.vsplit(b, (3, 4)))

[[ 4.  3.  4.  9.  0.  6.  3.  7.  2.  4.  4.  0.]
 [ 1.  8.  6.  3.  3.  2.  0.  4.  7.  5.  5.  4.]]
----------
[array([[ 4.,  3.,  4.,  9.],
       [ 1.,  8.,  6.,  3.]]), array([[ 0.,  6.,  3.,  7.],
       [ 3.,  2.,  0.,  4.]]), array([[ 2.,  4.,  4.,  0.],
       [ 7.,  5.,  5.,  4.]])]
----------
[array([[ 4.,  3.,  4.],
       [ 1.,  8.,  6.]]), array([[ 9.],
       [ 3.]]), array([[ 0.,  6.,  3.,  7.,  2.,  4.,  4.,  0.],
       [ 3.,  2.,  0.,  4.,  7.,  5.,  5.,  4.]])]
----------
[[ 4.  1.]
 [ 3.  8.]
 [ 4.  6.]
 [ 9.  3.]
 [ 0.  3.]
 [ 6.  2.]
 [ 3.  0.]
 [ 7.  4.]
 [ 2.  7.]
 [ 4.  5.]
 [ 4.  5.]
 [ 0.  4.]]
----------
[array([[ 4.,  1.],
       [ 3.,  8.],
       [ 4.,  6.],
       [ 9.,  3.]]), array([[ 0.,  3.],
       [ 6.,  2.],
       [ 3.,  0.],
       [ 7.,  4.]]), array([[ 2.,  7.],
       [ 4.,  5.],
       [ 4.,  5.],
       [ 0.,  4.]])]
----------
[array([[ 4.,  1.],
       [ 3.,  8.],
       [ 4.,  6.]]), array([[ 9.,  3.]]), array([[ 0.,  3.],
       [ 6.,

In [125]:
#浅复制
a = np.arange(12)
b = a
print(b is a)
b.shape = (3, 4)
print(a.shape)
print(id(a))
print(id(b))

True
(3, 4)
138329024
138329024


In [141]:
c = a.view()
print(c is a)
c.shape = (2, 6)
print(a.shape)
c[0, 4] = 1234
print(a)
print(id(a))
print(id(c))

False
(3, 4)
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
138329024
138328864


In [145]:
#深复制
d = c.copy()
print(d is c)
d[0, 0] = 9999
print(d)
print(c)

False
[[9999    1    2    3 1234    5]
 [   6    7    8    9   10   11]]
[[   0    1    2    3 1234    5]
 [   6    7    8    9   10   11]]


In [167]:
data = np.sin(np.arange(20)).reshape(5, -1)
print(data)
ind = data.argmax(axis=0)
print(ind)
data_max = data[ind, range(data.shape[1])]
print(data_max)

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
[2 0 3 1]
[ 0.98935825  0.84147098  0.99060736  0.6569866 ]


In [172]:
a = np.arange(0, 40, 10)
print(a)
b = np.tile(a, (2, 3))
print(b)

[ 0 10 20 30]
[[ 0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30]]


In [182]:
a = np.array([[4,3,5],[1,2,1]])
print(a)
print('----------')
b = np.sort(a, axis=1)
print(b)
print('----------')
a.sort(axis=1)
print(a)
print('----------')
a = np.array([4,3,1,2])
j = np.argsort(a)
print(j)
print('----------')
print(a[j])

[[4 3 5]
 [1 2 1]]
----------
[[3 4 5]
 [1 1 2]]
----------
[[3 4 5]
 [1 1 2]]
----------
[2 3 1 0]
----------
[1 2 3 4]
